-- =====================================================================
-- 01_snowflake_setup.sql
-- Database, schemas, warehouse, storage integration, external stage,
-- file format, raw table, service user, and RBAC ownership configuration.
-- =====================================================================

USE ROLE ACCOUNTADMIN;

-- 1. Virtual Warehouse Configuration
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WITH 
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Virtual warehouse for publisher intelligence ELT workloads';

-- 2. Database & Schema Scaffolding
CREATE DATABASE IF NOT EXISTS PUBLISHER_DWH;

-- RAW_INGEST: Landing schema for raw immutable S3 JSON payloads
CREATE SCHEMA IF NOT EXISTS PUBLISHER_DWH.RAW_INGEST;

-- Analytical schemas populated by dbt Core
CREATE SCHEMA IF NOT EXISTS PUBLISHER_DWH.STAGING;
CREATE SCHEMA IF NOT EXISTS PUBLISHER_DWH.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS PUBLISHER_DWH.MARTS;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE PUBLISHER_DWH;
USE SCHEMA RAW_INGEST;

-- 3. File Format for Gzipped JSON Payloads
CREATE OR REPLACE FILE FORMAT PUBLISHER_DWH.RAW_INGEST.FF_JSON_GZIP
    TYPE = 'JSON'
    COMPRESSION = 'GZIP'
    STRIP_OUTER_ARRAY = FALSE
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = TRUE
    COMMENT = 'File format for loading gzip-compressed JSON telemetry archives';

-- 4. Target Raw Table to Store VARIANT Payloads
CREATE TABLE IF NOT EXISTS PUBLISHER_DWH.RAW_INGEST.RAW_VIDEOS (
    raw_payload     VARIANT         COMMENT 'Raw extracted JSON object representing a single video snapshot',
    execution_date  DATE            COMMENT 'Logical execution/partition date from S3 path',
    ingested_at     TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP() COMMENT 'Timestamp when row was loaded into Snowflake',
    source_file     STRING          COMMENT 'Fully qualified S3 source file path'
);

-- 5. AWS IAM Cloud Storage Integration (sts:AssumeRole)
-- Replace <AWS_ACCOUNT_ID> and <S3_BUCKET_NAME> with your cloud infrastructure values
CREATE STORAGE INTEGRATION IF NOT EXISTS S3_INTEGRATION_RAW
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/<AWS_IAM_ROLE_NAME>'
    STORAGE_ALLOWED_LOCATIONS = ('s3://<S3_BUCKET_NAME>/raw/')
    COMMENT = 'AWS IAM assume-role storage integration for raw telemetry data lake';

-- 6. External S3 Stage
CREATE STAGE IF NOT EXISTS PUBLISHER_DWH.RAW_INGEST.STAGE_S3_RAW
    STORAGE_INTEGRATION = S3_INTEGRATION_RAW
    URL = 's3://<S3_BUCKET_NAME>/raw/'
    FILE_FORMAT = PUBLISHER_DWH.RAW_INGEST.FF_JSON_GZIP
    COMMENT = 'External stage pointing to raw S3 telemetry partition prefix';

-- 7. Service Role & Headless Service User Configuration
CREATE ROLE IF NOT EXISTS AIRFLOW_LOAD_ROLE;

-- Replace <RSA_PUBLIC_KEY> with your single-line public key string (excluding header/footer delimiters)
CREATE USER IF NOT EXISTS PUBLISHER_LOADER
    RSA_PUBLIC_KEY = '<RSA_PUBLIC_KEY>'
    DEFAULT_ROLE = AIRFLOW_LOAD_ROLE
    DEFAULT_WAREHOUSE = COMPUTE_WH
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Headless service account for automated pipeline loads via keypair auth';

GRANT ROLE AIRFLOW_LOAD_ROLE TO USER PUBLISHER_LOADER;

-- 8. RBAC Warehouse, Database, and Ingestion Privileges
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE AIRFLOW_LOAD_ROLE;
GRANT USAGE ON DATABASE PUBLISHER_DWH TO ROLE AIRFLOW_LOAD_ROLE;

-- Storage integration & Stage access
GRANT USAGE ON INTEGRATION S3_INTEGRATION_RAW TO ROLE AIRFLOW_LOAD_ROLE;
GRANT USAGE, READ ON STAGE PUBLISHER_DWH.RAW_INGEST.STAGE_S3_RAW TO ROLE AIRFLOW_LOAD_ROLE;
GRANT USAGE ON FILE FORMAT PUBLISHER_DWH.RAW_INGEST.FF_JSON_GZIP TO ROLE AIRFLOW_LOAD_ROLE;

-- Raw ingestion schema privileges
GRANT USAGE, CREATE STAGE ON SCHEMA PUBLISHER_DWH.RAW_INGEST TO ROLE AIRFLOW_LOAD_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLISHER_DWH.RAW_INGEST TO ROLE AIRFLOW_LOAD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA PUBLISHER_DWH.RAW_INGEST TO ROLE AIRFLOW_LOAD_ROLE;

-- 9. Analytical Schemas Ownership & Future Grants (dbt Execution)
-- Schema-level ownership ensures dbt can drop and replace models without privilege collisions
GRANT OWNERSHIP ON SCHEMA PUBLISHER_DWH.STAGING TO ROLE AIRFLOW_LOAD_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PUBLISHER_DWH.INTERMEDIATE TO ROLE AIRFLOW_LOAD_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PUBLISHER_DWH.MARTS TO ROLE AIRFLOW_LOAD_ROLE REVOKE CURRENT GRANTS;

-- Transfer ownership of any existing objects to the service role
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA PUBLISHER_DWH.STAGING TO ROLE AIRFLOW_LOAD_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA PUBLISHER_DWH.STAGING TO ROLE AIRFLOW_LOAD_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA PUBLISHER_DWH.INTERMEDIATE TO ROLE AIRFLOW_LOAD_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA PUBLISHER_DWH.INTERMEDIATE TO ROLE AIRFLOW_LOAD_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ALL TABLES IN SCHEMA PUBLISHER_DWH.MARTS TO ROLE AIRFLOW_LOAD_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA PUBLISHER_DWH.MARTS TO ROLE AIRFLOW_LOAD_ROLE REVOKE CURRENT GRANTS;

-- Automated future ownership grants for dbt table/view creations
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA PUBLISHER_DWH.STAGING TO ROLE AIRFLOW_LOAD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA PUBLISHER_DWH.STAGING TO ROLE AIRFLOW_LOAD_ROLE;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA PUBLISHER_DWH.INTERMEDIATE TO ROLE AIRFLOW_LOAD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA PUBLISHER_DWH.INTERMEDIATE TO ROLE AIRFLOW_LOAD_ROLE;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA PUBLISHER_DWH.MARTS TO ROLE AIRFLOW_LOAD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA PUBLISHER_DWH.MARTS TO ROLE AIRFLOW_LOAD_ROLE;